version: '3.12'
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8888:8888"  
      - "8000:8000" 
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /workspace
    command: sleep infinity  